USE [simpleproject-poc]
GO

/****** Object:  Table [dbo].[Cost_type]    Script Date: 06.02.2021 17:05:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cost_type](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Cost_type_name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Cost_type] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

