USE [simpleproject-poc]
GO

/****** Object:  Table [dbo].[Project_method]    Script Date: 05.03.2021 19:49:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Project_method](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Method_name] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Project_method] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

